eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8094

spring:
  application:
    name: api-gateway
 
 
  cloud:
    gateway:
      routes:
      - id: ADMIN-SERVICE
        uri: lb://ADMIN-SERVICE
        predicates:
           - Path=/admin/**
           
      - id: STUDENT-SERVICE
        uri: lb://STUDENT-SERVICE
        predicates:
           - Path=/student/**